### PR TITLE
Ban and Kick

### PR DESCRIPTION
**Pull request by jpsl00**
This needs guild schemas to be done before meging
- Add Kick and Ban commands

### CODE REVIEW

**Review by test137E29B — CHANGES_REQUESTED** [review]
Add Schema (merge-guard)

**Review by test137E29B — APPROVED** [review]
Good job :)

**Comment by jpsl00** [comment]
[Kick Command](https://trello.com/c/UHaHWCr2/8-kick-command)

**Comment by jpsl00** [comment]
[Ban Command](https://trello.com/c/VNcvntQy/2-ban-command)

**Pull request merged**
